// Comedy / welcome lines — 5+ per language code
// Shown on the home screen, tap to refresh

export const comedyLines: Record<string, string[]> = {
  en: [
    "Why did the smartphone go to school? To improve its 'cell'f! 📱",
    "My Wi-Fi went out for 5 minutes. I had to talk to my family. Terrifying. 📶",
    "I tried to write a joke about clocks… but I didn't think the timing was right. ⏰",
    "Money can't buy happiness, but it can buy an app with 23 tools. Pretty close! 😄",
    "I asked my calculator for a joke. It showed '8008'. Classic. 🧮",
    "Why is the ocean always on time? It follows the current! 🌊",
    "My doctor told me I needed more Vitamin D. So I downloaded Dark Mode. 🌙",
  ],
  hi: [
    "पत्नी ने पूछा - 'क्या आप मुझसे प्यार करते हैं?' मैंने कहा - 'हाँ, Google Maps से भी ज़्यादा!' 🗺️",
    "मेरी जेब में ₹10 थे, बहुत खुश था। फिर Inflation आई… अब भी ₹10 हैं, पर खुशी गायब! 💸",
    "Doctor ने कहा - 'फल खाओ।' मैंने Fruit Ninja खेला। Same thing ना? 🍎",
    "WiFi का password याद नहीं, पर बचपन की सारी कविताएं याद हैं। यही life है! 📶",
    "दोस्त बोला - 'बाल झड़ रहे हैं।' मैंने कहा - 'कम लोगों पर ज़्यादा जगह!' 😂",
    "सुबह उठना मुश्किल है… पर ZenSpace खोलना आसान है! ☀️",
  ],
  mr: [
    "बायकोने विचारले - 'आयुष्यात काय हवंय?' मी म्हणालो - 'WiFi Password!' 📶",
    "मराठी माणूस म्हणजे चहा आणि जिद्द — दोन्ही गरम! ☕",
    "परीक्षेत 0 मिळाला… पण शून्यातून सुरुवात करायची असते! 📝",
    "पुण्यात थंडी पडली म्हणजे खूप थंडी पडली! 🧣",
    "Smart phone आहे, पण आपण smart वापरतो का? ZenSpace तुम्हाला मदत करेल! 😄",
  ],
  ta: [
    "என் மனைவி கேட்டாள் - 'என்னை காதலிக்கிறீர்களா?' நான் சொன்னேன் - 'Google maps விட அதிகமாக!' 🗺️",
    "தூக்கம் வரவில்லை… ZenSpace திற, டூல்கள் பார், தூக்கம் வரும்! 😴",
    "பணம் மகிழ்ச்சியை வாங்க முடியாது, ஆனால் நல்ல app வாங்க முடியும்! 😄",
    "வலைத்தளம் மெதுவாக இருந்தது… நான் கோபமாக இருந்தேன்… பிறகு ZenSpace திறந்தேன்! ⚡",
    "சிரிக்க வைக்கும் app — இதுவே ZenSpace! 🌟",
  ],
  te: [
    "భార్య అడిగింది - 'మీరు నన్ను ప్రేమిస్తున్నారా?' నేను చెప్పాను - 'WiFi కంటే ఎక్కువగా!' 📶",
    "డబ్బు సంతోషాన్ని కొనలేదు, కానీ మంచి app కొనవచ్చు! 😄",
    "నేను జోక్ రాశాను... అది పని చేయలేదు... delete చేశాను! 😂",
    "సూర్యోదయంలో మేల్కొనడం కష్టం... ZenSpace తెరవడం సులభం! ☀️",
    "ప్రతి రోజు కొత్త అవకాశం — ZenSpace తో మొదలుపెట్టండి! 🌟",
  ],
  bn: [
    "বউ জিজ্ঞেস করল - 'আমাকে ভালোবাসো?' আমি বললাম - 'WiFi র চেয়ে বেশি!' 📶",
    "টাকা সুখ কিনতে পারে না, কিন্তু ভালো app কিনতে পারে! 😄",
    "সকালে উঠতে কষ্ট হয়... ZenSpace খুলতে নয়! ☀️",
    "বাংলা jokes সেরা... বাংলা apps ও সেরা! 🌟",
    "হাসুন, সুস্থ থাকুন, ZenSpace ব্যবহার করুন! 😊",
  ],
  gu: [
    "પત્ની એ પૂછ્યું - 'તમે મને પ્રેમ કરો છો?' મે' કહ્યું - 'WiFi કરતા વધુ!' 📶",
    "ગુજરાતી જ્યાં જાય ત્યાં ચા ની ગોળી બનાવે! ☕",
    "ZenSpace — ગુજ્ઝ apps ni best! 😄",
    "સવારે ઊઠવું મુશ્કેલ... ZenSpace ખોલવું સહેલું! ☀️",
    "હસો, ખુશ રહો, ZenSpace ની સાથે! 🌟",
  ],
  ml: [
    "ഭാര്യ ചോദിച്ചു - 'നിങ്ങൾ എന്നെ സ്നേഹിക്കുന്നുണ്ടോ?' ഞാൻ പറഞ്ഞു - 'WiFi യെക്കാൾ!' 📶",
    "ZenSpace — Kerala ന്റെ favourite app! 🌴",
    "ചിരിക്കൂ, ആനന്ദിക്കൂ, ZenSpace ഉപയോഗിക്കൂ! 😄",
    "ഒരു ദിവസം ഒരു jokes — ഡോക്ടറെ അകറ്റി നിർത്തും! 😂",
    "ZenSpace — ജീവിതം ലളിതമാക്കൂ! 🌟",
  ],
  kn: [
    "ಹೆಂಡತಿ ಕೇಳಿದಳು - 'ನೀವು ನನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೀರಾ?' ನಾನು ಹೇಳಿದೆ - 'WiFi ಗಿಂತ ಹೆಚ್ಚು!' 📶",
    "ZenSpace — Kannada app ಅತ್ಯುತ್ತಮ! 🌟",
    "ನಗು, ಸಂತಸ ಹೊಂದು, ZenSpace ಬಳಸು! 😄",
    "ಪ್ರತಿ ದಿನ ಹೊಸ ಆರಂಭ — ZenSpace ಜೊತೆ! ☀️",
    "ಜೋಕ್ ಕೇಳಿ, ಸ್ವಲ್ಪ ನಗು! 😂",
  ],
  pa: [
    "ਮੇਰੀ ਪਤਨੀ ਨੇ ਪੁੱਛਿਆ - 'ਕੀ ਤੁਸੀਂ ਮੈਨੂੰ ਪਿਆਰ ਕਰਦੇ ਹੋ?' ਮੈਂ ਕਿਹਾ - 'WiFi ਤੋਂ ਵੱਧ!' 📶",
    "ਪੰਜਾਬੀ ਬੰਦਾ — ਖਾਣਾ ਵੱਡਾ, ਦਿਲ ਹੋਰ ਵੀ ਵੱਡਾ! ❤️",
    "ZenSpace — ਪੰਜਾਬੀਆਂ ਲਈ ਬੈਸਟ app! 🌟",
    "ਸਵੇਰੇ ਉੱਠਣਾ ਔਖਾ... ZenSpace ਖੋਲ੍ਹਣਾ ਆਸਾਨ! ☀️",
    "ਹੱਸੋ, ਖੁਸ਼ ਰਹੋ, ZenSpace ਵਰਤੋ! 😄",
  ],
  ur: [
    "بیوی نے پوچھا - 'کیا آپ مجھ سے محبت کرتے ہیں؟' میں نے کہا - 'WiFi سے بھی زیادہ!' 📶",
    "پیسے خوشی نہیں خرید سکتے، لیکن اچھی app خرید سکتے ہیں! 😄",
    "ZenSpace — اردو بولنے والوں کی بہترین app! 🌟",
    "ہنسیں، خوش رہیں، ZenSpace استعمال کریں! 😊",
    "ہر صبح نئی شروعات — ZenSpace کے ساتھ! ☀️",
  ],
  es: [
    "¿Por qué los teléfonos nunca están solos? ¡Porque siempre tienen cobertura! 📱",
    "El dinero no compra la felicidad, pero sí una buena app. ¡Casi igual! 😄",
    "Mi Wi-Fi se cayó 5 minutos. Tuve que hablar con mi familia. ¡Aterrador! 📶",
    "ZenSpace — ¡La app que necesitabas! 🌟",
    "¡Empieza el día con una sonrisa y ZenSpace! ☀️",
  ],
  fr: [
    "Pourquoi les téléphones ne sont-ils jamais seuls? Ils ont toujours du réseau! 📱",
    "L'argent ne fait pas le bonheur, mais une bonne app, presque! 😄",
    "Mon Wi-Fi est tombé 5 minutes… J'ai dû parler à ma famille. Terrifiant! 📶",
    "ZenSpace — l'app dont vous aviez besoin! 🌟",
    "Commencez la journée avec le sourire! ☀️",
  ],
  de: [
    "Warum sind Smartphones nie allein? Weil sie immer Empfang haben! 📱",
    "Geld kauft kein Glück, aber eine gute App schon fast! 😄",
    "Mein WLAN war 5 Minuten weg… Ich musste mit meiner Familie reden. Erschreckend! 📶",
    "ZenSpace — die App, die du gebraucht hast! 🌟",
    "Starte den Tag mit einem Lächeln! ☀️",
  ],
  it: [
    "Perché i telefoni non sono mai soli? Perché hanno sempre copertura! 📱",
    "I soldi non comprano la felicità, ma una buona app sì! 😄",
    "ZenSpace — l'app di cui avevi bisogno! 🌟",
    "Inizia la giornata con un sorriso! ☀️",
    "La vita è bella — specialmente con ZenSpace! 🌈",
  ],
  pt: [
    "Por que os telefones nunca estão sozinhos? Porque sempre têm sinal! 📱",
    "Dinheiro não compra felicidade, mas compra uma boa app! 😄",
    "ZenSpace — o app que você precisava! 🌟",
    "Comece o dia com um sorriso! ☀️",
    "A vida é boa com ZenSpace! 🌈",
  ],
  nl: [
    "Waarom zijn telefoons nooit alleen? Ze hebben altijd bereik! 📱",
    "Geld koopt geen geluk, maar een goede app bijna! 😄",
    "ZenSpace — de app die je nodig had! 🌟",
    "Begin de dag met een glimlach! ☀️",
    "Het leven is mooi met ZenSpace! 🌈",
  ],
  ru: [
    "Почему телефоны никогда не бывают одни? У них всегда есть сеть! 📱",
    "Деньги не купят счастье, но хорошее приложение — почти! 😄",
    "ZenSpace — приложение, которое вам нужно! 🌟",
    "Начните день с улыбки! ☀️",
    "Жизнь прекрасна с ZenSpace! 🌈",
  ],
  tr: [
    "Telefonlar neden hiç yalnız değil? Çünkü hep çekimleri var! 📱",
    "Para mutluluk satın alamaz, ama iyi bir uygulama neredeyse! 😄",
    "ZenSpace — ihtiyacınız olan uygulama! 🌟",
    "Güneşli bir sabah, ZenSpace ile! ☀️",
    "Hayat güzel — ZenSpace ile daha da güzel! 🌈",
  ],
  ar: [
    "لماذا لا تكون الهواتف وحيدة أبدًا؟ لأن لديها دائمًا إشارة! 📱",
    "المال لا يشتري السعادة، لكن تطبيقًا جيدًا يقترب منها! 😄",
    "ZenSpace — التطبيق الذي تحتاجه! 🌟",
    "ابدأ يومك بابتسامة! ☀️",
    "الحياة جميلة مع ZenSpace! 🌈",
  ],
  zh: [
    "为什么手机从不孤单？因为它们总有信号！📱",
    "钱买不到幸福，但能买好应用！😄",
    "ZenSpace — 你需要的应用！🌟",
    "每天微笑，从ZenSpace开始！☀️",
    "生活美好，ZenSpace相伴！🌈",
  ],
  ja: [
    "スマホはなぜ一人じゃないの？電波があるから！📱",
    "お金で幸せは買えないけど、良いアプリは買える！😄",
    "ZenSpace — あなたに必要なアプリ！🌟",
    "笑顔で一日を始めよう！☀️",
    "ZenSpaceで人生を豊かに！🌈",
  ],
  ko: [
    "왜 스마트폰은 혼자가 아닐까요? 항상 신호가 있으니까요! 📱",
    "돈으로 행복을 살 수 없지만, 좋은 앱은 살 수 있어요! 😄",
    "ZenSpace — 당신에게 필요한 앱! 🌟",
    "웃으며 하루를 시작해요! ☀️",
    "ZenSpace와 함께 더 좋은 하루! 🌈",
  ],
  sw: [
    "Kwa nini simu haziko peke yake? Kwa sababu zina mtandao kila wakati! 📱",
    "Pesa haziwaletei furaha, lakini app nzuri inaweza! 😄",
    "ZenSpace — app unayohitaji! 🌟",
    "Anza siku yako na tabasamu! ☀️",
    "Maisha ni mazuri na ZenSpace! 🌈",
  ],
  or: [
    "ଫୋନ ଏକୁଟିଆ ନ ଥାଏ — ସବୁ ସମୟ ସିଗ୍ନାଲ ଅଛି! 📱",
    "ZenSpace — ତୁମ ପ୍ରିୟ app! 🌟",
    "ହସ, ଖୁସି ରହ, ZenSpace ବ୍ୟବହାର କର! 😄",
    "ପ୍ରତ୍ୟେକ ଦିନ ଏକ ନୂଆ ଆଶା! ☀️",
    "ଜୀବନ ସୁନ୍ଦର — ZenSpace ସହ! 🌈",
  ],
  as: [
    "ফোন কিয়নো একা নাথাকে? সদায় নেটৱৰ্ক থাকে! 📱",
    "ZenSpace — তোমাৰ প্ৰিয় app! 🌟",
    "হাঁহি, সুখী থাকা, ZenSpace ব্যৱহাৰ কৰা! 😄",
    "প্ৰতিটো দিন এক নতুন সুযোগ! ☀️",
    "জীৱন সুন্দৰ — ZenSpace ৰ সৈতে! 🌈",
  ],
  mai: [
    "फोन किएक एकल नहिं रहैत? हमेशा सिग्नल रहैत! 📱",
    "ZenSpace — अपनेक प्रिय app! 🌟",
    "हँसू, खुश रहू, ZenSpace उपयोग करू! 😄",
    "प्रत्येक दिन नव अवसर! ☀️",
    "जिनगी सुंदर अछि — ZenSpace संग! 🌈",
  ],
  ne: [
    "फोन किन एक्लो हुँदैन? सधैं नेटवर्क हुन्छ! 📱",
    "ZenSpace — तपाईंको मनपर्ने app! 🌟",
    "हाँस्नुस्, खुशी रहनुस्, ZenSpace प्रयोग गर्नुस्! 😄",
    "हर दिन नयाँ अवसर! ☀️",
    "जीवन सुन्दर छ — ZenSpace सँग! 🌈",
  ],
  kok: [
    "फोन एकट्याक नासता — सदाँ नेटवर्क आसता! 📱",
    "ZenSpace — तुमची आवडती app! 🌟",
    "हास, सुखी रावा, ZenSpace वापरा! 😄",
    "हर दीस नवो मौको! ☀️",
    "जीण सुंदर — ZenSpace सांगाता! 🌈",
  ],
  sd: [
    "فون ڇو اڪيلو نه هوندو آهي؟ هميشه نيٽورڪ هوندو آهي! 📱",
    "ZenSpace — توهان جي پسنديده app! 🌟",
    "کير ڪيو، خوش رهو، ZenSpace استعمال ڪيو! 😄",
    "هر ڏينهن نئون موقعو! ☀️",
    "زندگي سٺي آهي — ZenSpace سان! 🌈",
  ],
};

export function getComedyLine(langCode: string): string[] {
  return comedyLines[langCode] ?? comedyLines["en"];
}
