kind = "mobile"
previewPath = "/app/"
title = "ZenSpace App"
version = "1.0.0"
id = "artifacts/fittrack"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/app/" ]
localPort = 25772

[services.development]
run = "pnpm --filter @workspace/fittrack run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fittrack", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/fittrack", "run", "serve" ]

[services.env]
PORT = "25772"
BASE_PATH = "/app/"
